### PR TITLE
Added option to enable BL-Touch to work properly

### PR DESCRIPTION
**Pull request by STiXzoOR**
I added the option to easily enable BL-Touch sensor for those who wan to use it instead of EZABL without changing anything other than uncommenting the `#define BLTOUCH` and `#define SERVO0_PIN` in `configuration.h`

### CODE REVIEW

**Comment by houseofbugs** [comment]
We added in beta support for the BL Touch. Please test with the latest version on here. :) We don't have a BL Touch Probe so we cannot verify that it works. But it compiles.

**Comment by STiXzoOR** [comment]
Glad to hear that but one question. Wouldn't this line: `#if DISABLED(POWER_LOSS_RECOVERY) && DISABLED(BLTOUCH)` disable the **S_CURVE_ACCELERATION** on the non 1284p boards as well?

**Comment by houseofbugs** [comment]
Check the latest one on here. I just re-vamped how it's being handled and allocating space.

**Comment by houseofbugs** [comment]
Check the latest release on here. Should all be working now. :)

**Pull request closed without merging**
